apiVersion: v1
kind: Service
metadata:
  name: av-parser-web-svc
spec:
  selector:
    app: av-parser-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: LB_IP #patched via kustomize