apiVersion: v1
kind: Namespace
metadata:
  name: mqtt
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-config
  namespace: mqtt
data:
  mosquitto.conf: |
    # MQTT listener
    listener 1883
    protocol mqtt
    # Websocket listener
    listener 9001
    protocol websockets
    allow_anonymous false
    password_file /mosquitto/config/password.txt
    persistence true
    autosave_interval 600
    autosave_on_changes true
    persistence_location /mosquitto/data/
    log_dest file /mosquitto/log/mosquitto.log
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mqtt
  namespace: mqtt
spec:
  selector:
    matchLabels:
      app: mqtt 
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      imagePullSecrets:
      - name: mqtt-registry-credentials
      nodeSelector:
        type: agent
      securityContext:
        fsGroup: 1883  # Ensures group ownership for NFS/SMB volumes so user 1883 can access files
      volumes:
      - name: mqtt-password
        secret:
          secretName: mqtt-password
      - name: mqtt-config
        configMap:
          name: mqtt-config
      containers:
      - name: mqtt
        image: eclipse-mosquitto:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: mqtt-pvc
          mountPath: /mosquitto/data
        - name: mqtt-password
          mountPath: /mosquitto/config/password.txt
          subPath: mqtt-password.txt
        - name: mqtt-config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
        ports:
        - containerPort: 1883
        - containerPort: 9001
      - name: mqtt-web
        image: emqx/mqttx-web:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
  volumeClaimTemplates:
  - metadata:
      name: mqtt-pvc
      namespace: mqtt
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "nfs"
      resources:
        requests:
          storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-exporter
  namespace: mqtt
spec:
  selector:
    matchLabels:
      app: mosquitto-exporter 
  template:
    metadata:
      labels:
        app: mosquitto-exporter
    spec:
      nodeSelector:
        type: agent
        kubernetes.io/arch: arm64
      containers:
      - name: mosquitto-exporter
        image: jhawk7/mosquitto-exporter:latest #using personal image for arm compatibility
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: mosquitto-exporter-env
        ports:
        - containerPort: 9234