apiVersion: v1
kind: Namespace
metadata:
  name: mqtt
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mqtt
  namespace: mqtt
spec:
  selector:
    matchLabels:
      app: mqtt 
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      imagePullSecrets:
      - name: mqtt-registry-credentials
      nodeSelector:
        type: agent
        kubernetes.io/hostname: node1
      securityContext:
        fsGroup: 1883  # smb doesn't support chown or chmod for files; fsgroup will set group ownership of the mounted volume
      initContainers:
      - name: init-pvc
        image: alpine # runs as root by default doesn't have user 1883 (user for mqtt), run as root and change permissions to allow mqtt to read/write
        imagePullPolicy: IfNotPresent
        command:
          - sh
          - -c
          - |
            echo "Copying init files"
            mkdir -p /mosquitto/data
            mkdir -p /mosquitto/log
            mkdir -p /mosquitto/config
            cp -rL /secrets/* /mosquitto/config
            mv /mosquitto/config/mqtt-passwd.txt /mosquitto/config/passwd.txt
        volumeMounts:
        - name: mqtt-pvc
          mountPath: /mosquitto
        - name: mqtt-secret-volume
          mountPath: /secrets
      volumes:
      - name: mqtt-secret-volume
        secret:
          secretName: mqtt-init-secret-files
          defaultMode: 0777
      containers:
      - name: mqtt
        image: eclipse-mosquitto:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: mqtt-pvc
          mountPath: /mosquitto
        ports:
        - containerPort: 1883
        - containerPort: 9001
      - name: mqtt-web
        image: emqx/mqttx-web:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
  volumeClaimTemplates:
  - metadata:
      name: mqtt-pvc
      namespace: mqtt
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-path" #using local path due to smb woes
      resources:
        requests:
          storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-exporter
  namespace: mqtt
spec:
  selector:
    matchLabels:
      app: mosquitto-exporter 
  template:
    metadata:
      labels:
        app: mosquitto-exporter
    spec:
      nodeSelector:
        type: agent
        kubernetes.io/arch: arm64
      containers:
      - name: mosquitto-exporter
        image: jhawk7/mosquitto-exporter:latest #using personal image for arm compatibility
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: mosquitto-exporter-env
        ports:
        - containerPort: 9234