apiVersion: v1
kind: Service
metadata:
  name: go-bills-api-svc
  namespace: apps
spec:
  selector:
    app: go-bills-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  loadBalancerIP: LB_IP #patched via kustomize