apiVersion: v1
kind: Namespace
metadata:
  name: node-red
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node-red
  namespace: node-red
spec:
  selector:
    matchLabels:
      app: node-red 
  template:
    metadata:
      labels:
        app: node-red
    spec:
      nodeSelector:
        type: agent
      securityContext:
        fsGroup: 1000 
      containers:
      - name: node-red
        image: nodered/node-red:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: node-red-pvc
          mountPath: /data
        ports:
        - containerPort: 1880
  volumeClaimTemplates:
  - metadata:
      name: node-red-pvc
      namespace: node-red
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "nfs-retain"
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: node-red-svc
  namespace: node-red
spec:
  selector:
    app: node-red
  type: LoadBalancer
  loadBalancerIP: LB_IP #patched via kustomize
  ports:
  - name: http
    port: 1880
    targetPort: 1880
    protocol: TCP