apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- mqtt-sub-client.argocd.yaml
- go-counter-consumer.argocd.yaml
- go-counter-producer.argocd.yaml
- dotnetapi.argocd.yaml
- imageUpdater.yaml
